---
# Ceedling 1.x project configuration
:project:
  :build_root: build
  :test_file_prefix: test_
  :use_mocks: FALSE
  :use_test_preprocessor: :none
  :use_backtrace: :none

:paths:
  :test:
    - +:test/**
  :source:
    - src/**
  :include:
    - include/**

:defines:
  :test:
    - UNIT_TEST

:libraries:
  :system:
    - m

:plugins:
  :enabled:
    - report_tests_pretty_stdout
